# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

conda:
  environment: docs/environment.yml

python:
  version: 3.8
  install:
    - method: pip
      path: .

